### PR TITLE
Made libyaml into a submodule and now build from that.

### PR DESCRIPTION
**Pull request by suetanvil**
Also added the configure scripts in a tarball so that the user does
not need to have autoconf installed and included the tool used to
generate this tarball.  (These files are included in the official
source distribution of libyaml but are not in the git repository.)

And made an attempt at fixing the CI configuration.  I have zero
experience with Github's CI so this is a crapshoot.

### CODE REVIEW

**Comment by k0kubun** [comment]
> Also added the configure scripts in a tarball so that the user does not need to have autoconf installed and included the tool used to generate this tarball

I don't want mruby-yaml to be responsible for it. Could you consider not including libyaml-autoconf.tar.gz in this repository? Building mruby-yaml requires a bunch of dependencies anyway and autoconf should be just one of them.

**Comment by suetanvil** [comment]
I'll make that change.

**Comment by suetanvil** [comment]
I've pushed the update.  It *should* work now.

(I did it twice because I forgot to mention in the first commit message that there was also a (possible) fix for the CI script.)

**Review by k0kubun — APPROVED** [review]
Thank you!

**Pull request merged**
