### PR TITLE
Added support for proper types

### PR DESCRIPTION
**Pull request by IceDragon200**
YAML should now be able to load true, false and nil

``` yaml

---
foo: true
bar: false
baz: nil
```

Result:

``` ruby
{
  "foo" => true,
  "bar" => false,
  "baz" => nil
}
```

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Code looks good, but what if I want the string "true", etc? What about using language-independent types?
http://yaml.org/type/null.html
http://yaml.org/type/bool.html

**Comment by IceDragon200** [comment]
@AndrewBelt my latest commit should address all the issues you mentioned, if you want the string true,

``` yaml
my_true_string: "true"
my_true_value: true
```

In addition, I fixed a issue I had some months ago, with YAML loading strings with numbers in them as numbers instead of Strings.

**Comment by pbosetti** [comment]
If I may comment on this issue, it would be nice supporting all the cases reported in the links pasted above by @AndrewBelt, e.g. `~|null|Null|NULL` and likewise for booleans.

**Comment by archseer** [comment]
@pbosetti It does. https://github.com/AndrewBelt/mruby-yaml/pull/5/files#diff-8f7f121e494e598c7381ac969199d73bR152

**Comment by IceDragon200** [comment]
Fixed an issue where scalar aliases would break mapping keys.

EG.

``` yaml
---
bounding_box:
  x: 0
  y: 12
  w: 32
  h: 20
```

Would result in:

``` ruby
{ 
  "bounding_box" => { 
    "x" => 0, 
    true => 12, 
    "w" => 32, 
    "h" => 20 
  } 
}
```

If the node appears as a mapping key, the only alias supported will be `~` aka. (`nil`)

**Comment by AndrewBelt** [comment]
There does seem to be some mention of tags in libyaml, but those definitions aren't used anywhere in the source.
https://bitbucket.org/xi/libyaml/src/2b9156756423e967cfd09a61d125d883fca6f4f2/include/yaml.h?at=default#cl-664

So the multiple `streql` method must be the way to do it. It might be worth removing all the multiple defines and just supporting them by default, or adding an option to `YAML.parse` to turn them off.

**Pull request merged**
