### PR TITLE
Imported libyaml source code into this repo.

### PR DESCRIPTION
**Pull request by suetanvil**
Also updated mrbgem.rake to build from it instead of fetching the source
tarball from a website with curl.

The rationale for this to make the build more repeatable.  Currently,
the build could fail if the pyyaml.org website goes down or has its
files rearranged or if the build machine loses network external
access.  Alternately, if a bad actor broke into the site and altered
the site to (for example) add a backdoor, that would propagate to this
gem's users.

By keeping the libyaml source code here, we guarantee that the sources
are present and unmodified.

### CODE REVIEW

**Comment by k0kubun** [comment]
> Currently, the build could fail if the pyyaml.org website goes down or has its files rearranged or if the build machine loses network external access.

mruby's build process doesn't work if you don't have access to github.com. Do you accept github.com dependency unlike pyyaml.org dependency? If that's the case, how about using `git clone` to get libyaml?

If you're packaging mruby-yaml so that you don't need to repeat `git clone` on build, how about using `git submodule` to include libyaml as a part of the mruby-yaml package? This is because, once you have a hard copy, you cannot trust the copy is a real libyaml. Somebody touching this repository could randomly modify the content, and then getting rid of the fork could be really hard. So I'd like to avoid having the copy.

**Comment by suetanvil** [comment]
I understand your concern.  However, I maintain that it is easy enough to document that the parser should not diverge from the upstream source and reject any pull request that modifies the parser sources.  That being said, if you prefer it, I will update the pull request to instead retrieve the parser source from a separate git repository.

For what it's worth, I have in fact removed github.com as a dependency for the project that inspired this.  I use a modified `build_config.rb` and some  scripts to build from identical clones of the remote dependencies in a git repository that I control, plus locally-cached copies. Adding the parser to the rgem source ends up being the simplest solution for me so I plan to keep using it.

**Comment by k0kubun** [comment]
> if you prefer it, I will update the pull request to instead retrieve the parser source from a separate git repository.

Yes, please use `git submodule`. As long as you have the ability to remove github.com dependency from mruby-yaml itself, you should be able to fulfill the purpose if you use `git submodule` to include libyaml. I don't wanna spend any second on "documenting that the parser should not diverge from the upstream source" or "rejecting any pull request that modifies the parser sources".

**Comment by suetanvil** [comment]
I'm closing this because I ended up creating a new pull request at <https://github.com/mrbgems/mruby-yaml/pull/26> in order to remove noise from the history.  As discussed here, it adds libyaml's repo as a submodule.

**Pull request closed without merging**
